export const ACTION_CLIENT_ADD = 'CLIENT_ADD';
export const ACTION_CLIENT_REMOVE = 'CLIENT_REMOVE';
export const ACTION_CLIENT_EDIT = 'CLIENT_EDIT';
export const ACTION_CLIENT_LIST = 'CLIENT_LIST';

export const ACTION_SCHEDULE_ADD = 'SCHEDULE_ADD';
export const ACTION_SCHEDULE_REMOVE = 'SCHEDULE_REMOVE';
export const ACTION_SCHEDULE_EDIT = 'SCHEDULE_EDIT';
export const ACTION_SCHEDULE_LIST = 'SCHEDULE_LIST';

